DROP TABLE IF EXISTS tweet_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS tweets;
DROP TABLE IF EXISTS users_auth;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE "users" (
  "id" serial PRIMARY KEY,
  "email" varchar(200) UNIQUE,
  "first_name" varchar(150),
  "last_name" varchar(150)
);

CREATE TABLE "users_auth"(
  id serial PRIMARY KEY,
  users_id INT REFERENCES users(id),
  hash TEXT
);

CREATE TABLE "tweets" (
  "id" serial PRIMARY KEY,
  "author_id" int REFERENCES users(id),
  "image_url" text,
  "title" varchar(100),
  "body" varchar(240)
);

CREATE TABLE "comments" (
  "id" serial PRIMARY KEY,
  "author_id" int REFERENCES users(id),
  "tweet_id" int REFERENCES tweets(id),
  "comment" varchar(240)
);

CREATE TABLE "tweet_likes" (
  "id" serial PRIMARY KEY,
  "tweet_id" int REFERENCES tweets(id),
  "user_id" int REFERENCES users(id)
);

INSERT INTO users(first_name,last_name,email) VALUES ('Dominik','Mattia','dmattia0@google.com.hk');
INSERT INTO users(first_name,last_name,email) VALUES ('Arlana','McLanaghan','amclanaghan1@nbcnews.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Gusti','Spoors','gspoors2@liveinternet.ru');
INSERT INTO users(first_name,last_name,email) VALUES ('Micky','Gilbertson','mgilbertson3@foxnews.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Malinde','Haggarty','mhaggarty4@cam.ac.uk');
INSERT INTO users(first_name,last_name,email) VALUES ('Filippa','Jodlkowski','fjodlkowski5@craigslist.org');
INSERT INTO users(first_name,last_name,email) VALUES ('Putnem','Dmitrienko','pdmitrienko6@goodreads.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Rodolph','Schelle','rschelle7@netvibes.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Renaldo','Vanne','rvanne8@multiply.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Alberik','Fold','afold9@liveinternet.ru');
INSERT INTO users(first_name,last_name,email) VALUES ('Antonina','Antonikov','aantonikova@ow.ly');
INSERT INTO users(first_name,last_name,email) VALUES ('Corny','Clemmey','cclemmeyb@netlog.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Glenna','Pezey','gpezeyc@cam.ac.uk');
INSERT INTO users(first_name,last_name,email) VALUES ('Perceval','Holliar','pholliard@whitehouse.gov');
INSERT INTO users(first_name,last_name,email) VALUES ('Barty','Olle','bollee@twitter.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Essy','Creser','ecreserf@live.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Daryl','Chieze','dchiezeg@answers.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Thedric','Mitchelhill','tmitchelhillh@cbslocal.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Frederica','Lavis','flavisi@360.cn');
INSERT INTO users(first_name,last_name,email) VALUES ('Noak','Arpe','narpej@google.co.jp');
INSERT INTO users(first_name,last_name,email) VALUES ('Ashla','Longstreet','alongstreetk@php.net');
INSERT INTO users(first_name,last_name,email) VALUES ('Rolf','Packman','rpackmanl@china.com.cn');
INSERT INTO users(first_name,last_name,email) VALUES ('Jeth','Deble','jdeblem@timesonline.co.uk');
INSERT INTO users(first_name,last_name,email) VALUES ('Rena','Brissard','rbrissardn@etsy.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Chryste','Chastan','cchastano@marriott.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Fernando','Eyes','feyesp@gravatar.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Zonnya','Crosthwaite','zcrosthwaiteq@surveymonkey.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Wait','Ebbins','webbinsr@dot.gov');
INSERT INTO users(first_name,last_name,email) VALUES ('Verene','Birrel','vbirrels@mail.ru');
INSERT INTO users(first_name,last_name,email) VALUES ('Wilhelmine','Rosenwald','wrosenwaldt@wordpress.org');
INSERT INTO users(first_name,last_name,email) VALUES ('Barbabas','Ledwitch','bledwitchu@aol.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Chan','Vannucci','cvannucciv@issuu.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Antoni','Langfield','alangfieldw@t-online.de');
INSERT INTO users(first_name,last_name,email) VALUES ('Delaney','Ace','dacex@ox.ac.uk');
INSERT INTO users(first_name,last_name,email) VALUES ('Reade','Weston','rwestony@feedburner.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Albert','Poynton','apoyntonz@ebay.co.uk');
INSERT INTO users(first_name,last_name,email) VALUES ('Yulma','Hilldrup','yhilldrup10@rediff.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Noach','Reay','nreay11@globo.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Anabal','Rastall','arastall12@cocolog-nifty.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Saunderson','Dautry','sdautry13@java.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Marlowe','Burnsides','mburnsides14@umn.edu');
INSERT INTO users(first_name,last_name,email) VALUES ('Katerine','Teml','kteml15@blogspot.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Cyrille','Hassen','chassen16@opera.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Cameron','Clery','cclery17@columbia.edu');
INSERT INTO users(first_name,last_name,email) VALUES ('Cyndie','Burcombe','cburcombe18@chicagotribune.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Stormie','Drewitt','sdrewitt19@va.gov');
INSERT INTO users(first_name,last_name,email) VALUES ('Kele','Kirk','kkirk1a@cdc.gov');
INSERT INTO users(first_name,last_name,email) VALUES ('Bryan','Wooldridge','bwooldridge1b@ovh.net');
INSERT INTO users(first_name,last_name,email) VALUES ('Dido','Bartali','dbartali1c@squarespace.com');
INSERT INTO users(first_name,last_name,email) VALUES ('Harper','Holyland','hholyland1d@google.cn');

INSERT INTO users_auth(users_id,hash) VALUES (1,'1BoWhDZPxmZmZHnPLBV9uop32p7E5t6XYZ');
INSERT INTO users_auth(users_id,hash) VALUES (2,'13Ynv9JL5gtWf1rS7eVsPajaXMDek9g61G');
INSERT INTO users_auth(users_id,hash) VALUES (3,'1BsGJ78rW1sRfQUbtcNJ1bSJX4FC2aaHrh');
INSERT INTO users_auth(users_id,hash) VALUES (4,'1FMaUnzy65EiHqcyy2dVgJsg37tFEv3JXq');
INSERT INTO users_auth(users_id,hash) VALUES (5,'1NVZAQB23QzathSveUFFb4taJCCDDY3SjE');
INSERT INTO users_auth(users_id,hash) VALUES (6,'1F26dMKjt9CjMcsxiFYfMEtrXP71FU8gZG');
INSERT INTO users_auth(users_id,hash) VALUES (7,'1M5m6BfAtgNSqpV7SKdNsUigwzt6M8qY2m');
INSERT INTO users_auth(users_id,hash) VALUES (8,'1thMLrcEpRNVCN5gJS2vYadAjetJbJSq9');
INSERT INTO users_auth(users_id,hash) VALUES (9,'1JfF5wPv9q5h7gjhdDmSnuycn8B9Nuxitq');
INSERT INTO users_auth(users_id,hash) VALUES (10,'1S9HQt7VrLgjXd3UE7whcaL62XTmFHYbV');
INSERT INTO users_auth(users_id,hash) VALUES (11,'1HfikGECxBBCNjfqCkUbFg1wpMdALmoxT7');
INSERT INTO users_auth(users_id,hash) VALUES (12,'12PezqX7hvXmH1FxXCSvcykEPsGbQTBXYC');
INSERT INTO users_auth(users_id,hash) VALUES (13,'1KFkhoiN1FLzGdeDu7JimMEGVqv1GKKVsn');
INSERT INTO users_auth(users_id,hash) VALUES (14,'1CgiKuGk78fHqiar3QFJHk8XyNJAWfhPqo');
INSERT INTO users_auth(users_id,hash) VALUES (15,'14YEnmbCSgqtx82RgUcDrE9Q3NF4gikmty');
INSERT INTO users_auth(users_id,hash) VALUES (16,'1F34PrUkWJXFBxt2ZuLCiUjEcHL8PgQ1u3');
INSERT INTO users_auth(users_id,hash) VALUES (17,'1Fjq3hm4tYTDfXtWDH6vhrVnBufaP5uBrN');
INSERT INTO users_auth(users_id,hash) VALUES (18,'1D6ntcWB3DNhXfSHVBFXxxXAoUzkMU1Teo');
INSERT INTO users_auth(users_id,hash) VALUES (19,'1L1bW7bRFaTpPAVHtLdAFnMtmuCyYCRtTu');
INSERT INTO users_auth(users_id,hash) VALUES (20,'17PMUJHcHiNc3LfthtWassuUq2fcQv2XVq');
INSERT INTO users_auth(users_id,hash) VALUES (21,'1554riTaubFovYnnqxuBYd6thmV2Zd1ffP');
INSERT INTO users_auth(users_id,hash) VALUES (22,'1DR9tDdGrDQJCSewRkd3Xcoee5fPJs6jEB');
INSERT INTO users_auth(users_id,hash) VALUES (23,'18R8gbNbLbbBEvFEW7ShfGiz9L57zab5WF');
INSERT INTO users_auth(users_id,hash) VALUES (24,'13e9kbNgkue8YQkrAM9Ua2S8sdCszoy7Yd');
INSERT INTO users_auth(users_id,hash) VALUES (25,'1PgKyWUPSqaP7roUbUH3mJV2q6ZkYuTM1W');
INSERT INTO users_auth(users_id,hash) VALUES (26,'1Eq1HJKqQN2sUdLeeKXvQVBPQoVTT7Ab5y');
INSERT INTO users_auth(users_id,hash) VALUES (27,'135V2xTkuT4F4mviwZKbN2N3tWLQpsAMuq');
INSERT INTO users_auth(users_id,hash) VALUES (28,'1DPJbkgS5JBdhoqWWqxMyQxFMjFJK15a8F');
INSERT INTO users_auth(users_id,hash) VALUES (29,'16FPyxPtbuELctoQ5sCSPRY4v3mK6HTS8T');
INSERT INTO users_auth(users_id,hash) VALUES (30,'17aBBCU28ez3aXtMLhKaNN3RWyRELoSfAS');
INSERT INTO users_auth(users_id,hash) VALUES (31,'1H7CgWei4LEQU3ehJqtm8xSV3fTBrBXPBF');
INSERT INTO users_auth(users_id,hash) VALUES (32,'1HqE45p4etWV9DkB9VU1TSQz4wbnZe4Nh2');
INSERT INTO users_auth(users_id,hash) VALUES (33,'12Z9vqRrof5kyzhtt3pLXvkuEsyEJxBfpY');
INSERT INTO users_auth(users_id,hash) VALUES (34,'1H7TkRVbrzXyxQWHaLdv8F9WeJBD1d8ejT');
INSERT INTO users_auth(users_id,hash) VALUES (35,'15pY1X57hVhHQEhTuqoaGkGXoXKkiV2bqe');
INSERT INTO users_auth(users_id,hash) VALUES (36,'1DasUnhwUNVK4u9zTum8EFmzD2chVG6WeS');
INSERT INTO users_auth(users_id,hash) VALUES (37,'1CC4maMaSKcfB2biFLy38XAuCzhfXLRkML');
INSERT INTO users_auth(users_id,hash) VALUES (38,'1BWUCWuLfSCMrAfAbxPPwjDXqwkrYXjh3L');
INSERT INTO users_auth(users_id,hash) VALUES (39,'1KinFjtVhFrkr3JBXKVGDjFYuh3HsoRE1c');
INSERT INTO users_auth(users_id,hash) VALUES (40,'14Rn8eYykcg2RtAw31yicSxyDtXy33eXjT');
INSERT INTO users_auth(users_id,hash) VALUES (41,'1Eoe6uf9UBsE2TLBZuXmCqRQx3sqmxizZW');
INSERT INTO users_auth(users_id,hash) VALUES (42,'14AqxWFBmCox7yyLkxWJZEtkWhrk5yRbDj');
INSERT INTO users_auth(users_id,hash) VALUES (43,'1KhqdfyF8s2PZCqy9ikFBwThrEptxHeDXs');
INSERT INTO users_auth(users_id,hash) VALUES (44,'1HEJEXNQqrAdEKh7vLRJJ6Ny94Qk4Ho5be');
INSERT INTO users_auth(users_id,hash) VALUES (45,'1LspZ8jZssA48Nmf8meLtTuKEK4aEMZH7J');
INSERT INTO users_auth(users_id,hash) VALUES (46,'14wAXh7cgV15cniX3ZHhHPHWoiBDmmoin1');
INSERT INTO users_auth(users_id,hash) VALUES (47,'1Dkt3rCbqguaohqy6kh1W9z6qtM7q3i6G8');
INSERT INTO users_auth(users_id,hash) VALUES (48,'13gKigiUR9VFhpZh5Pro578rRY9PWWL37f');
INSERT INTO users_auth(users_id,hash) VALUES (49,'19p8uaUG9y88oBW4ETViSmkbLfiPpwHhPr');
INSERT INTO users_auth(users_id,hash) VALUES (50,'161rKJHdZCoxhXpdxmzZohRgS2GVA2U177');


INSERT INTO tweets(author_id,title,body,image_url) VALUES (47,'Fix San','Cross-platform composite instruction set','http://dummyimage.com/129x131.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (10,'Cardguard','Innovative 5th generation structure','http://dummyimage.com/207x138.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (27,'Ventosanzap','Multi-tiered zero administration framework','http://dummyimage.com/223x237.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (31,'Zathin','Diverse didactic migration','http://dummyimage.com/197x137.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (26,'Holdlamis','Compatible empowering array','http://dummyimage.com/161x180.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (25,'Cookley','Persevering user-facing core','http://dummyimage.com/144x229.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (3,'Bamity','Open-source coherent collaboration','http://dummyimage.com/236x200.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (46,'Ronstring','User-centric static data-warehouse','http://dummyimage.com/200x210.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (25,'Bamity','Enterprise-wide neutral neural-net','http://dummyimage.com/177x110.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (48,'Trippledex','Advanced bandwidth-monitored instruction set','http://dummyimage.com/157x142.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (31,'Subin','Polarised intangible software','http://dummyimage.com/236x225.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (42,'Pannier','Customer-focused human-resource protocol','http://dummyimage.com/230x187.bmp/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (46,'Keylex','Balanced uniform flexibility','http://dummyimage.com/191x125.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (41,'Zaam-Dox','Persevering impactful framework','http://dummyimage.com/120x114.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (7,'Stronghold','Monitored dynamic task-force','http://dummyimage.com/119x127.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (22,'Keylex','Business-focused tangible knowledge base','http://dummyimage.com/165x132.png/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (27,'Fixflex','Ameliorated foreground knowledge base','http://dummyimage.com/112x184.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (50,'Tresom','Secured non-volatile open architecture','http://dummyimage.com/130x192.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (4,'Duobam','Grass-roots fresh-thinking attitude','http://dummyimage.com/205x175.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (41,'Biodex','Assimilated national software','http://dummyimage.com/166x136.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (39,'Y-Solowarm','Universal impactful utilisation','http://dummyimage.com/102x224.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (34,'Cardguard','Business-focused maximized parallelism','http://dummyimage.com/215x173.png/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (24,'Biodex','Customizable client-driven product','http://dummyimage.com/183x223.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (41,'Bitwolf','Sharable intermediate project','http://dummyimage.com/168x116.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (13,'Biodex','Robust fault-tolerant functionalities','http://dummyimage.com/244x200.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (30,'Sonsing','Open-source fresh-thinking open architecture','http://dummyimage.com/182x248.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (25,'Latlux','Programmable web-enabled migration','http://dummyimage.com/190x192.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (3,'Tresom','Front-line multi-state budgetary management','http://dummyimage.com/150x188.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (32,'Treeflex','Universal transitional budgetary management','http://dummyimage.com/199x176.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (3,'Pannier','Business-focused composite policy','http://dummyimage.com/145x225.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (44,'Hatity','Fundamental analyzing structure','http://dummyimage.com/207x157.bmp/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (10,'Asoka','Business-focused encompassing collaboration','http://dummyimage.com/205x191.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (24,'Trippledex','Profound 4th generation hub','http://dummyimage.com/101x236.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (24,'Cardify','Future-proofed content-based instruction set','http://dummyimage.com/107x119.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (40,'Transcof','Reduced regional algorithm','http://dummyimage.com/164x110.png/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (31,'Matsoft','Versatile global adapter','http://dummyimage.com/155x171.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (13,'Hatity','Polarised needs-based framework','http://dummyimage.com/103x129.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (19,'Y-Solowarm','Optional reciprocal policy','http://dummyimage.com/203x184.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (32,'Cardguard','Multi-lateral value-added pricing structure','http://dummyimage.com/154x179.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (4,'Otcom','Vision-oriented demand-driven knowledge user','http://dummyimage.com/247x183.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (7,'Veribet','Decentralized attitude-oriented circuit','http://dummyimage.com/226x244.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (46,'Viva','Digitized 24/7 collaboration','http://dummyimage.com/183x188.png/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (31,'Bamity','Mandatory bottom-line adapter','http://dummyimage.com/140x101.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (41,'Opela','Grass-roots content-based ability','http://dummyimage.com/228x114.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (43,'Overhold','Team-oriented client-server focus group','http://dummyimage.com/128x159.png/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (45,'Tres-Zap','Team-oriented exuding hierarchy','http://dummyimage.com/177x222.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (9,'Bitchip','Focused dynamic architecture','http://dummyimage.com/111x137.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (2,'Overhold','Digitized directional Graphical User Interface','http://dummyimage.com/121x144.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (4,'Solarbreeze','Polarised static open system','http://dummyimage.com/101x242.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (38,'Redhold','Fundamental system-worthy capacity','http://dummyimage.com/106x197.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Holdlamis','Stand-alone 4th generation task-force','http://dummyimage.com/142x189.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (12,'Veribet','Function-based holistic groupware','http://dummyimage.com/146x227.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Regrant','Implemented even-keeled structure','http://dummyimage.com/196x233.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (6,'Zamit','Switchable tangible website','http://dummyimage.com/117x242.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (20,'Lotlux','Total hybrid productivity','http://dummyimage.com/147x212.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (28,'Voyatouch','Diverse secondary infrastructure','http://dummyimage.com/200x117.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (7,'Stringtough','Re-engineered mission-critical initiative','http://dummyimage.com/104x231.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (8,'Asoka','Team-oriented bifurcated hub','http://dummyimage.com/224x140.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (6,'Bitwolf','Realigned holistic infrastructure','http://dummyimage.com/116x167.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (49,'Alphazap','Realigned directional matrices','http://dummyimage.com/159x237.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (20,'Gembucket','Robust 5th generation open architecture','http://dummyimage.com/111x193.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (27,'Viva','Synergistic intermediate local area network','http://dummyimage.com/240x167.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (30,'Mat Lam Tam','Grass-roots neutral superstructure','http://dummyimage.com/122x161.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (49,'Sonair','Realigned bifurcated alliance','http://dummyimage.com/143x212.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (27,'Otcom','Open-architected user-facing functionalities','http://dummyimage.com/184x135.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (25,'Stim','Fully-configurable solution-oriented alliance','http://dummyimage.com/247x151.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (9,'Konklux','Visionary systematic definition','http://dummyimage.com/235x120.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (43,'Aerified','Streamlined maximized system engine','http://dummyimage.com/223x123.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (12,'Subin','Networked homogeneous pricing structure','http://dummyimage.com/102x199.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (48,'Matsoft','Team-oriented cohesive capability','http://dummyimage.com/167x147.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (43,'Aerified','Monitored multimedia strategy','http://dummyimage.com/173x134.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (13,'Mat Lam Tam','Versatile 3rd generation Graphic Interface','http://dummyimage.com/205x125.png/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (36,'Stringtough','Multi-tiered neutral attitude','http://dummyimage.com/179x152.png/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (46,'Stim','Integrated 3rd generation customer loyalty','http://dummyimage.com/142x129.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (41,'Tresom','Persevering attitude-oriented circuit','http://dummyimage.com/180x169.bmp/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (2,'Zamit','Customizable attitude-oriented open system','http://dummyimage.com/175x196.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (38,'Viva','User-centric intermediate architecture','http://dummyimage.com/197x120.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (16,'Temp','Fundamental neutral capacity','http://dummyimage.com/223x160.bmp/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Tempsoft','Cross-platform human-resource monitoring','http://dummyimage.com/193x248.jpg/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (14,'Pannier','Inverse 5th generation data-warehouse','http://dummyimage.com/223x208.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (25,'Y-find','Compatible clear-thinking encoding','http://dummyimage.com/102x222.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (14,'Fixflex','Sharable client-driven toolset','http://dummyimage.com/229x160.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (22,'Latlux','Future-proofed motivating matrix','http://dummyimage.com/135x113.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (14,'It','Virtual national architecture','http://dummyimage.com/183x156.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Cookley','Grass-roots multi-state pricing structure','http://dummyimage.com/211x115.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (36,'Stronghold','Automated eco-centric migration','http://dummyimage.com/134x244.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (15,'Trippledex','Fully-configurable optimizing alliance','http://dummyimage.com/101x181.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (31,'Biodex','Cross-platform 6th generation attitude','http://dummyimage.com/167x177.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (8,'Trippledex','Synergized stable support','http://dummyimage.com/236x167.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Gembucket','Robust holistic process improvement','http://dummyimage.com/142x248.bmp/ff4444/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (39,'Zoolab','Exclusive global database','http://dummyimage.com/216x189.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (33,'Hatity','Intuitive fresh-thinking challenge','http://dummyimage.com/165x125.jpg/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (23,'Prodder','Pre-emptive even-keeled projection','http://dummyimage.com/128x105.png/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (29,'Transcof','Reverse-engineered methodical functionalities','http://dummyimage.com/228x127.bmp/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (42,'Sonair','Profound mission-critical policy','http://dummyimage.com/231x145.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (32,'Holdlamis','User-centric heuristic benchmark','http://dummyimage.com/192x149.png/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (21,'Cardify','Decentralized systemic Graphical User Interface','http://dummyimage.com/124x144.jpg/dddddd/000000');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (43,'Stringtough','Stand-alone 24 hour pricing structure','http://dummyimage.com/148x179.bmp/cc0000/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (49,'Y-find','Vision-oriented didactic internet solution','http://dummyimage.com/246x232.jpg/5fa2dd/ffffff');
INSERT INTO tweets(author_id,title,body,image_url) VALUES (38,'Flexidy','Synergistic bifurcated customer loyalty','http://dummyimage.com/166x147.jpg/cc0000/ffffff');

INSERT INTO comments(author_id,tweet_id,comment) VALUES (46,81,'Pre-emptive incremental emulation');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (41,4,'Business-focused client-server structure');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (30,4,'Focused executive success');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (10,99,'Synchronised modular initiative');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (2,41,'Customer-focused exuding database');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (29,95,'Distributed 5th generation synergy');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (28,35,'Enhanced coherent strategy');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (17,14,'Decentralized methodical methodology');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (10,49,'Managed value-added algorithm');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,61,'Switchable asynchronous info-mediaries');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (36,61,'Horizontal systemic intranet');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (19,72,'Adaptive 5th generation migration');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (24,62,'Configurable bandwidth-monitored superstructure');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (47,62,'Optimized intermediate workforce');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (25,89,'Ameliorated real-time encoding');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (29,38,'Synchronised 3rd generation circuit');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (17,84,'Realigned composite paradigm');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (44,64,'Streamlined clear-thinking help-desk');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (32,33,'Networked background matrices');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (18,44,'Grass-roots needs-based Graphical User Interface');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,5,'Reverse-engineered impactful extranet');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (41,30,'Universal full-range solution');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (14,65,'Fully-configurable asynchronous open architecture');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (17,27,'Polarised leading edge matrix');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (44,35,'Multi-channelled regional collaboration');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (7,26,'Profit-focused contextually-based challenge');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (23,63,'Ergonomic systematic framework');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (8,54,'Upgradable solution-oriented complexity');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (15,72,'Cross-group intermediate open system');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (6,35,'Open-architected hybrid process improvement');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (12,97,'Innovative context-sensitive data-warehouse');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (11,20,'Versatile fault-tolerant portal');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (13,44,'Inverse dedicated conglomeration');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,99,'Optional executive analyzer');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (5,52,'Assimilated attitude-oriented methodology');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (49,81,'Synergized uniform task-force');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (13,80,'Integrated cohesive structure');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (8,61,'Self-enabling executive knowledge user');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (16,74,'Virtual next generation toolset');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (7,33,'Team-oriented mobile open architecture');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (4,13,'Polarised global extranet');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (5,2,'Profit-focused leading edge standardization');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (28,81,'Balanced empowering structure');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (37,40,'Organic actuating infrastructure');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,22,'Function-based client-driven orchestration');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (22,86,'Virtual foreground alliance');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (41,14,'Pre-emptive uniform alliance');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,9,'Operative composite flexibility');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (7,77,'Right-sized multi-state collaboration');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (3,11,'Ameliorated logistical projection');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (15,84,'Centralized leading edge methodology');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (17,98,'Diverse hybrid moratorium');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (3,28,'Synergized systematic Graphic Interface');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (12,59,'Organized modular adapter');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (35,20,'User-friendly coherent concept');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (30,60,'Persevering multi-tasking implementation');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (12,41,'Exclusive multi-state complexity');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (42,56,'Devolved content-based emulation');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (8,20,'Up-sized 24/7 architecture');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (1,26,'Polarised optimizing product');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (16,37,'Horizontal holistic Graphic Interface');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (21,42,'Re-engineered tertiary info-mediaries');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (33,33,'Robust grid-enabled knowledge user');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (11,43,'Seamless zero tolerance flexibility');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (25,33,'Persevering upward-trending firmware');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (47,28,'Optimized zero tolerance array');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (3,60,'User-centric real-time paradigm');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (42,12,'Organized grid-enabled throughput');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (13,52,'Self-enabling contextually-based projection');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (50,31,'Reverse-engineered value-added framework');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (46,59,'Sharable optimal circuit');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (19,70,'Managed global synergy');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (33,61,'Cross-platform well-modulated hierarchy');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (20,21,'User-friendly non-volatile analyzer');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (23,29,'Down-sized methodical info-mediaries');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (43,50,'Synergistic directional function');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (5,67,'Future-proofed demand-driven toolset');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (28,100,'Automated zero defect portal');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (5,44,'Multi-lateral eco-centric forecast');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (25,33,'Open-source 4th generation frame');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (20,88,'Versatile incremental moderator');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (16,93,'Visionary scalable contingency');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (10,37,'Customizable solution-oriented internet solution');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (23,51,'De-engineered real-time data-warehouse');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (16,24,'Reduced 24 hour product');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (29,2,'Polarised content-based success');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (42,85,'Enterprise-wide full-range open architecture');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (42,43,'Devolved local portal');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (33,24,'Diverse scalable portal');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (39,44,'Secured hybrid neural-net');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (19,56,'Intuitive human-resource help-desk');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (23,33,'Ergonomic impactful concept');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (24,81,'Proactive responsive methodology');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (19,12,'Reduced multi-state attitude');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (39,66,'Extended analyzing matrix');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (33,74,'Visionary foreground hub');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (17,66,'Exclusive actuating hardware');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (10,86,'Multi-tiered bi-directional attitude');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (45,80,'Mandatory full-range model');
INSERT INTO comments(author_id,tweet_id,comment) VALUES (13,93,'Open-source explicit firmware');

INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,77);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,65);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,85);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (8,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,29);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,16);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,89);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,90);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,24);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,65);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,60);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,48);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,26);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,15);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,82);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,66);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (8,12);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,90);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,65);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,100);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,1);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,71);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,33);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,68);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,100);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,66);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,34);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,71);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,85);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,15);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,20);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,42);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,28);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,87);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,63);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,3);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,35);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,4);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,95);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,98);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,16);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,63);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,55);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (18,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,37);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,46);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,71);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,40);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,95);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (7,68);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,95);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,35);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,15);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,19);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,70);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,75);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,7);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,7);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,42);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,48);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,95);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,83);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,99);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,5);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,11);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,53);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,53);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,16);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,69);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (7,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,15);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,90);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,29);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,85);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,46);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,17);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,19);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,33);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,55);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,57);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,80);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,35);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,82);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,19);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,53);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,24);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,40);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,12);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,28);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,100);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,5);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,65);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,29);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,63);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,70);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,73);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,29);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,4);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,35);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,57);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,9);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,88);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,17);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,9);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,38);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,65);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,34);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,9);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,75);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,57);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,9);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,40);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,69);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,19);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,73);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,52);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,68);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,72);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,16);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,44);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (8,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,87);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (8,78);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,52);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,29);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,3);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,70);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (18,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (8,4);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,100);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,34);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,89);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,4);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,40);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,21);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,53);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,97);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,55);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,1);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,76);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,37);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,66);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,3);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,99);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,99);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,41);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,23);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,83);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (7,55);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,20);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,39);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,46);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,87);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,20);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,73);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,97);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,66);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,37);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,38);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,17);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,41);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,89);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,86);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,26);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,73);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,15);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,33);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,21);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (18,21);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,37);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,21);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,23);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,83);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (19,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,28);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (7,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (45,13);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,72);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,38);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,51);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,12);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,47);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,54);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (18,27);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,98);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (22,74);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,36);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,77);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,5);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,78);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,21);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (16,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,24);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (23,39);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,4);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,98);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (34,36);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (30,49);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,37);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,99);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (12,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,85);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,14);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,94);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,3);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,70);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,75);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,12);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,48);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,64);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (44,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (7,89);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,32);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,12);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (5,33);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,85);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (3,28);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (24,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,71);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,33);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (14,90);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,87);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,9);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,30);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,1);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,39);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,45);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,76);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (38,11);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,31);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,2);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,38);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,98);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,55);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (33,44);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (25,5);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,93);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (15,22);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,92);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,69);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,62);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (43,35);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (40,72);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,48);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (50,6);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (28,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,75);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (46,41);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,8);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,97);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (6,91);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (29,41);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,99);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (11,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (36,61);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (48,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (10,89);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,82);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (13,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (39,68);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,59);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,96);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (17,95);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,58);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (37,50);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (26,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,41);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (2,1);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (47,67);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (4,43);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,38);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (1,25);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (21,81);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (35,84);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,56);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (32,79);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (9,5);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (42,18);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (31,44);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (41,14);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (20,72);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (49,10);
INSERT INTO tweet_likes(user_id,tweet_id) VALUES (27,75);
